### ISSUE TITLE
Does not work with contexts without types

### ISSUE THREAD

**Issue by gburel** [rafoo/dedukti-mode#2]
On 

```
#NAME foo.
i : Type.
def f : i -> i.
[x] f x --> x.
(; f ;)
```

When trying to evaluate f, raise 

`dedukti-rule-context-at-point: Search failed: ":"`

Does work when using explicit types in contexts of rules.

**Comment by rafoo** [comment]
To explain what is going on, I need to explain roughly how evaluation works (or should work).

We start with a term t selected in a Dedukti file (Γ, C[t], Γ'). In general, t may refer to constants declared in Γ, and to rewrite rule variables and bound variables declared (with or without types) in C[.].
We syntactically recover the typing information in C[.] as a typing context Δ and we ask Dedukti to check the file (Γ, Δ, #SNF t).

When the evaluation feature of dedukti-mode was developped, explicit types in contexts and on binders were mandatory so it was always possible to collect the type of each variable occuring in the evaluated term in a purely syntactic way.

There are several issues at hand here:
- If t contains free variables that are not explicitely typed, this approach can not work.
- Even if C[.] binds variables that are not explicitely typed but do not occur in t, the approach fails because we do not filter them when producing Δ.
- There is a bug in function `dedukti-rulep` which is supposed to indicate whether or not point is inside a rewrite rule and if so where the rule context is. It is used to compute Δ: if point is in a rewrite rule, we declare the variables in the context of the rewrite rule. It actually indicates wether a rewrite rule is present before point and if so where the context of the last rewrite rule before point is.

The 3rd point is easy to fix and will solve the issue for this example. The second point is harder and the first one impossible without either delegating some work to Dedukti or reimplementing parts of Dedukti in Lisp.

Better error reporting would also be welcome.
